### ISSUE TITLE
Is there any way to contact you via email?

### ISSUE THREAD

**Issue by alexanderschnitzler** [Cabacos/centro-ambiental#1]
Is this account still active and is there any chance one can contact you?
I visited Cabacos last year and want to get in contact with manu.

Best regards,
Alex

**Comment by ghost** [comment]
​Yes, it's active!

​I actually set this up as a guest, and I'm not sure now if I have Manu's
contact info. I'd like to have that anyway, so I'm asking a friend:

Diego, do you have Manu's phone number or email?


-- Spencer

**Comment by ghost** [comment]
Here's Manu's phone number:

https://⌫.ws/47lkKqgp

That link will only work once, so make sure to save it after you open it.

**Comment by alexanderschnitzler** [comment]
It worked.
Thank you very much!
